Removing -q

diff --git a/activity-translations b/activity-translations
--- a/activity-translations
+++ b/activity-translations
@@ -50,14 +50,14 @@ fi
 
 # fetch latest translations
 cd po
-wget -q https://translate.sugarlabs.org/projects/$A/
-wget_output=$?
-if [ "$wget_output" -ne 0 ] ; then
-    echo  "Translations could not be fetched.\n"
-        if [ "$wget_output" -eq 8 ]; then
-        echo  "Incorrect ProjectName, check if ProjectName is one listed on translate.sugarlabs.org"
+wget https://translate.sugarlabs.org/projects/$A/
+wget_status=$?
+if [ "$wget_status" -ne 0 ] ; then
+    echo  "Translations could not be fetched, wget failed."
+    if [ "$wget_status" -eq 8 ]; then
+        echo  "Server issued an error response. Checking if ProjectName is one listed on translate.sugarlabs.org might be helpful."
         exit 2
-        fi
+    fi
     exit 2
 fi
 
